apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-app
spec:
  replicas: 3  # Número de réplicas del pod
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-container
          image: 654654589924.dkr.ecr.eu-north-1.amazonaws.com/grupo01/frontend-web:<IMAGE_TAG>  # Imagen Docker, el tag se reemplaza dinámicamente
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-app
spec:
  type: LoadBalancer  # Expone la aplicación públicamente
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: frontend-app